import { Service } from "./types";

export interface CategorizedService extends Service {
  category: string;
  nameZh: string;
  descriptionZh: string;
  categoryZh: string;
}

export const SERVICES: CategorizedService[] = [
  // --- Foot Reflexology ---
  {
    id: "foot-30",
    category: "Foot Reflexology",
    categoryZh: "足部反射疗法",
    name: "30min Foot Reflexology",
    nameZh: "30分钟足部反射疗法",
    description: "Relaxing session focusing on key tension relief points for feet and calves.",
    descriptionZh: "专注于足部和小腿关键压力释放点的放松疗程。",
    price: 40,
    duration: 30,
    image: "https://i.ibb.co/GffJnss7/uploads-abe8b6ac1b335500d861-uploads-ebe27b296916be3f30e4-c870x524.webp",
  },
  {
    id: "foot-45",
    category: "Foot Reflexology",
    categoryZh: "足部反射疗法",
    name: "45min Foot Reflexology",
    nameZh: "45分钟足部反射疗法",
    description: "Extended session for deep relaxation of the feet and lower legs.",
    descriptionZh: "延长疗程，为足部和小腿提供深度放松。",
    price: 50,
    duration: 45,
    image: "https://i.ibb.co/GffJnss7/uploads-abe8b6ac1b335500d861-uploads-ebe27b296916be3f30e4-c870x524.webp",
  },
  {
    id: "foot-60",
    category: "Foot Reflexology",
    categoryZh: "足部反射疗法",
    name: "1hr Foot Reflexology",
    nameZh: "1小时足部反射疗法",
    description: "Starts with a thorough 15-minute neck, shoulders, arms, and hand massage. Sea salt foot bath. 45-minute calves and feet reflexology.",
    descriptionZh: "包含15分钟颈部、肩部、手臂和手部按摩。海盐足浴。45分钟小腿和足部反射疗法。",
    price: 55,
    duration: 60,
    image: "https://i.ibb.co/GffJnss7/uploads-abe8b6ac1b335500d861-uploads-ebe27b296916be3f30e4-c870x524.webp",
  },
  {
    id: "foot-60-pro",
    category: "Foot Reflexology",
    categoryZh: "足部反射疗法",
    name: "1hr Foot Reflexology Pro",
    nameZh: "1小时专业足部反射疗法",
    description: "Starts with a thorough 15-minute neck, shoulders, arms, and hand massage. Handcrafted bubble foot spa with shea & cocoa butter. 10-minute scalp massage.",
    descriptionZh: "包含15分钟颈肩手臂按摩。手工乳木果和可可脂泡泡足浴。10分钟头皮按摩。",
    price: 65,
    duration: 60,
    image: "https://i.ibb.co/GffJnss7/uploads-abe8b6ac1b335500d861-uploads-ebe27b296916be3f30e4-c870x524.webp",
  },

  // --- Scalp Treatment ---
  {
    id: "scalp-45",
    category: "Scalp Treatment",
    categoryZh: "头皮护理",
    name: "45min Scalp Treatment",
    nameZh: "45分钟头皮护理",
    description: "Essential scalp cleaning and massage ritual.",
    descriptionZh: "基础头皮清洁与按摩仪式。",
    price: 65,
    duration: 45,
    image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "scalp-60",
    category: "Scalp Treatment",
    categoryZh: "头皮护理",
    name: "1hr Scalp Treatment",
    nameZh: "1小时头皮护理",
    description: "Includes scented essential oil of choice, scalp, shoulder, and neck massage, scalp cleaning, hands and arms detox reflexology, and cleansing facial.",
    descriptionZh: "包括精油选择、头皮肩颈按摩、头皮清洁、手臂排毒反射疗法及面部清洁。",
    price: 79,
    duration: 60,
    image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "scalp-75",
    category: "Scalp Treatment",
    categoryZh: "头皮护理",
    name: "75min Scalp Treatment",
    nameZh: "75分钟头皮护理",
    description: "Extended scalp therapy with deep tissue neck and shoulder work.",
    descriptionZh: "延长头皮护理，包含深层组织颈肩按摩。",
    price: 95,
    duration: 75,
    image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "scalp-90",
    category: "Scalp Treatment",
    categoryZh: "头皮护理",
    name: "90min Scalp Treatment",
    nameZh: "90分钟头皮护理",
    description: "The ultimate head spa experience with comprehensive massage and premium treatments.",
    descriptionZh: "极致头疗体验，包含全方位按摩和顶级护理。",
    price: 110,
    duration: 90,
    image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&q=80&w=800",
  },

  // --- Combination ---
  {
    id: "combo-sf-60",
    category: "Combination",
    categoryZh: "组合套餐",
    name: "1hr Shoulder + Foot",
    nameZh: "1小时 肩颈 + 足疗",
    description: "30 min shoulder + 30 min foot.",
    descriptionZh: "30分钟肩颈 + 30分钟足疗。",
    price: 70,
    duration: 60,
    image: "https://i.ibb.co/6c66HSkw/uploads-8820a2499cd6fc35f334-1759798457939.jpg",
  },
  {
    id: "combo-sf-90",
    category: "Combination",
    categoryZh: "组合套餐",
    name: "90min Shoulder + Foot",
    nameZh: "90分钟 肩颈 + 足疗",
    description: "45 min shoulder + 45 min foot.",
    descriptionZh: "45分钟肩颈 + 45分钟足疗。",
    price: 105,
    duration: 90,
    image: "https://i.ibb.co/6c66HSkw/uploads-8820a2499cd6fc35f334-1759798457939.jpg",
  },
  {
    id: "combo-scf-75",
    category: "Combination",
    categoryZh: "组合套餐",
    name: "75min Scalp + Foot",
    nameZh: "75分钟 头疗 + 足疗",
    description: "45 min scalp + 30 min foot.",
    descriptionZh: "45分钟头疗 + 30分钟足疗。",
    price: 95,
    duration: 75,
    image: "https://i.ibb.co/6c66HSkw/uploads-8820a2499cd6fc35f334-1759798457939.jpg",
  },
  {
    id: "combo-scf-90-bal",
    category: "Combination",
    categoryZh: "组合套餐",
    name: "90min Scalp + Foot (Balanced)",
    nameZh: "90分钟 头疗 + 足疗 (均衡)",
    description: "45 min scalp + 45 min foot.",
    descriptionZh: "45分钟头疗 + 45分钟足疗。",
    price: 105,
    duration: 90,
    image: "https://i.ibb.co/6c66HSkw/uploads-8820a2499cd6fc35f334-1759798457939.jpg",
  },
  {
    id: "combo-scf-90-focus",
    category: "Combination",
    categoryZh: "组合套餐",
    name: "90min Scalp + Foot (Scalp Focus)",
    nameZh: "90分钟 头疗 + 足疗 (专注头疗)",
    description: "60 min scalp + 30 min foot.",
    descriptionZh: "60分钟头疗 + 30分钟足疗。",
    price: 110,
    duration: 90,
    image: "https://i.ibb.co/6c66HSkw/uploads-8820a2499cd6fc35f334-1759798457939.jpg",
  },
  {
    id: "combo-scf-120",
    category: "Combination",
    categoryZh: "组合套餐",
    name: "2hr Combination",
    nameZh: "2小时 头疗 + 足疗",
    description: "60 min scalp + 60 min foot.",
    descriptionZh: "60分钟头疗 + 60分钟足疗。",
    price: 129,
    duration: 120,
    image: "https://i.ibb.co/6c66HSkw/uploads-8820a2499cd6fc35f334-1759798457939.jpg",
  },

  // --- Classical Facial ---
  {
    id: "facial-45",
    category: "Classical Facial",
    categoryZh: "经典面部护理",
    name: "45min Classical Facial",
    nameZh: "45分钟经典面部护理",
    description: "Express facial for a quick glow and refresh.",
    descriptionZh: "快速面部护理，让肌肤迅速焕发光彩。",
    price: 68,
    duration: 45,
    image: "https://i.ibb.co/hxBPfKvH/uploads-f036c601881cb0fcc1c8-uploads-f1555a0a37b03b563797-Screenshot-2025-09-16-at-2-14-46-PM.png",
  },
  {
    id: "facial-60",
    category: "Classical Facial",
    categoryZh: "经典面部护理",
    name: "1hr Classical Facial",
    nameZh: "1小时经典面部护理",
    description: "A timeless skincare practice to cleanse, nourish, and rejuvenate.",
    descriptionZh: "经典的护肤疗程，清洁、滋养并焕活肌肤。",
    price: 78,
    duration: 60,
    image: "https://i.ibb.co/hxBPfKvH/uploads-f036c601881cb0fcc1c8-uploads-f1555a0a37b03b563797-Screenshot-2025-09-16-at-2-14-46-PM.png",
  },
  {
    id: "facial-90",
    category: "Classical Facial",
    categoryZh: "经典面部护理",
    name: "90min Classical Facial",
    nameZh: "90分钟经典面部护理",
    description: "Extended facial treatment with extra massage and premium masks.",
    descriptionZh: "延长的面部护理，包含额外的按摩和高级面膜。",
    price: 115,
    duration: 90,
    image: "https://i.ibb.co/hxBPfKvH/uploads-f036c601881cb0fcc1c8-uploads-f1555a0a37b03b563797-Screenshot-2025-09-16-at-2-14-46-PM.png",
  },

  // --- Deep Cleaning ---
  {
    id: "deep-cleaning",
    category: "Deep Cleaning",
    categoryZh: "深层清洁",
    name: "Deep Cleaning",
    nameZh: "深层清洁护理",
    description: "Intensive 75-minute facial focusing on pore health and skin clarity.",
    descriptionZh: "75分钟密集面部护理，专注于毛孔健康和皮肤透亮。",
    price: 98,
    duration: 75,
    image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&q=80&w=800",
  },

  // --- Collagen Hydration ---
  {
    id: "collagen-hydration",
    category: "Collagen Hydration",
    categoryZh: "胶原蛋白保湿",
    name: "Collagen Hydration",
    nameZh: "胶原蛋白保湿护理",
    description: "Luxurious 75-minute treatment to restore elasticity and deep moisture.",
    descriptionZh: "75分钟奢华护理，恢复肌肤弹性和深度保湿。",
    price: 118,
    duration: 75,
    image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&q=80&w=800",
  }
];